nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Patricia Agudelo-Romero
  description: pipEline for Viral assEmbly and chaRactEriSaTion
  force: false
  is_nfcore: true
  name: everest
  org: nf-core
  outdir: .
  version: 1.0dev
