#=================================================
# PATCH EXISTING BIOCONTAINER
#=================================================

#NOTE: Make sure the version is correct
FROM quay.io/biocontainers/virsorter:2.2.4--pyhdfd78af_1

#NOTE: Install screed
RUN pip install screed
